version: "3.9"

services:
  app:
    build:
      args:
        APP_CONTEXT_PATH: $APP_CONTEXT_PATH
        DOCKER_IMAGE_CONTEXT_PATH: $DOCKER_IMAGE_CONTEXT_PATH
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: $FROSTNOVA_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/app/Dockerfile
    container_name: frostnova_app
    environment:
      DEBUG_LOG: /var/log/app.log
      DEFAULT_LOCALE: "en_US"
      ENVIRONMENT: "development"
      ERROR_REPORTING: "true"
      FORCE_HTTPS: "false"
      SITE_NAME: "Frost Nova"
    networks:
      - external
      - internal
    volumes:
      - $APP_DIRECTORY:/home/dockeruser/app
      - $DOCKER_DIRECTORY/images/app/php.ini:/usr/local/etc/php/php.ini
      - $APP_LOG_DIRECTORY:/var/log

  http-proxy:
    build:
      args:
        DOCKER_IMAGE_CONTEXT_PATH: $DOCKER_IMAGE_CONTEXT_PATH
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: $FROSTNOVA_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/http-proxy/Dockerfile
    container_name: frostnova_http-proxy
    networks:
      - external
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - $DOCKER_DIRECTORY/images/http-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - $HTTP_PROXY_LOG_DIRECTORY:/var/log/nginx

networks:
  internal:
  external:
